### PR TITLE
skeleton setup

### PR DESCRIPTION
**Pull request by ChadFusco**

### CODE REVIEW

**Review by maxpeterson96 — APPROVED** [review]
looks good thank you Chad

**Review by kimberlywycheung — APPROVED** [review]
Looks great!

**Review by svemi — APPROVED** [review]
Looks good! EDIT: Oops didn't see two approvals

**Review by maxpeterson96 — APPROVED** [review]
looks great!

**Review by maxpeterson96 — APPROVED** [review]
Approved!

**Pull request merged**
